--- #YAML:1.0
name:               Catalyst-Model-Xapian
version:            0.06
abstract:           Catalyst model for Search::Xapian.
author:
    - Jonathan Rockway <mramberg@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst:        5.30
    Data::Page:      0
    Encode:          0
    MRO::Compat:     0
    Search::Xapian:  0.9.2.4
    Storable:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
