---
name: Catalyst-Model-Xapian
version: 0.03
author:
  - 'Marcus Ramberg <mramberg@cpan.org>'
abstract: Catalyst model for Search::Xapian.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst: 5.30
  Data::Page: 0
  Encode: 0
  Search::Xapian: 0.9.2.4
  Storable: 0
provides:
  Catalyst::Helper::Model::Xapian:
    file: lib/Catalyst/Helper/Model/Xapian.pm
  Catalyst::Model::Xapian:
    file: lib/Catalyst/Model/Xapian.pm
    version: 0.03
  Catalyst::Model::Xapian::Result:
    file: lib/Catalyst/Model/Xapian/Result.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
